[workspace]
resolver = "2"
members = [
	"Conformance",
	"Sources/TuringMachine",
	"Sources/WebAssembly/*",
	"IR/*",
	"Targets/Json",
	"Targets/Luau/*",
	"Targets/LuaJIT/*",
	"Targets/LuaNoFFI/*",
	"CLI",
	"Tools/*",
	"tests/manual/self-hosting-luanoffi-builder",
]

[workspace.dependencies]
list = { git = "https://github.com/SovereignSatellite/RustListDataStructure.git", rev = "a236bf9" }
set = { git = "https://github.com/SovereignSatellite/RustSetDataStructure.git", rev = "b82ef8c" }

cranelift-isle = { version = "0.124.1", default-features = false }

hashbrown = { version = "0.16.0", default-features = false, features = [
	"default-hasher",
	"equivalent",
	"inline-more",
] }

wasmparser = { version = "0.235.0", default-features = false }

[workspace.lints.rust]
absolute_paths_not_starting_with_crate = "forbid"
bare_trait_objects = "forbid"
break_with_label_and_loop = "forbid"
closure_returning_async_block = "forbid"
dead_code = "deny"
double_negations = "forbid"
elided_lifetimes_in_paths = "forbid"
ellipsis_inclusive_range_patterns = "forbid"
explicit_outlives_requirements = "forbid"
for_loops_over_fallibles = "forbid"
impl_trait_redundant_captures = "forbid"
macro_use_extern_crate = "forbid"
mismatched_lifetime_syntaxes = "forbid"
missing_abi = "forbid"
missing_copy_implementations = "forbid"
missing_docs = "deny"
named_arguments_used_positionally = "forbid"
non_ascii_idents = "forbid"
non_camel_case_types = "deny"
non_local_definitions = "forbid"
non_shorthand_field_patterns = "forbid"
non_snake_case = "deny"
non_upper_case_globals = "forbid"
path_statements = "forbid"
redundant_imports = "forbid"
redundant_lifetimes = "forbid"
redundant_semicolons = "forbid"
single_use_lifetimes = "forbid"
trivial_casts = "forbid"
trivial_numeric_casts = "forbid"
unit_bindings = "forbid"
unsafe_op_in_unsafe_fn = "deny"
unused_allocation = "deny"
unused_assignments = "deny"
unused_associated_type_bounds = "deny"
unused_braces = "deny"
unused_crate_dependencies = "deny"
unused_doc_comments = "deny"
unused_extern_crates = "deny"
unused_features = "deny"
unused_import_braces = "deny"
unused_imports = "forbid"
unused_labels = "deny"
unused_lifetimes = "deny"
unused_macro_rules = "deny"
unused_macros = "deny"
unused_must_use = "deny"
unused_mut = "deny"
unused_parens = "deny"
unused_qualifications = "deny"
unused_unsafe = "deny"
unused_variables = "deny"
while_true = "forbid"

[workspace.lints.clippy]
alloc_instead_of_core = "forbid"
allow_attributes = "forbid"
allow_attributes_without_reason = "forbid"
almost_complete_range = "forbid"
assertions_on_constants = "forbid"
assertions_on_result_states = "forbid"
assign_op_pattern = "forbid"
assigning_clones = "forbid"
bind_instead_of_map = "forbid"
blanket_clippy_restriction_lints = "forbid"
blocks_in_conditions = "forbid"
bool_assert_comparison = "forbid"
bool_comparison = "forbid"
bool_to_int_with_if = "forbid"
borrow_as_ptr = "forbid"
borrow_deref_ref = "forbid"
borrowed_box = "forbid"
box_collection = "forbid"
box_default = "forbid"
boxed_local = "forbid"
branches_sharing_code = "forbid"
builtin_type_shadow = "forbid"
byte_char_slices = "forbid"
bytes_count_to_len = "forbid"
bytes_nth = "forbid"
case_sensitive_file_extension_comparisons = "forbid"
cast_lossless = "forbid"
cast_possible_truncation = "forbid"
cast_possible_wrap = "forbid"
cast_precision_loss = "forbid"
cast_sign_loss = "forbid"
chars_last_cmp = "forbid"
chars_next_cmp = "forbid"
checked_conversions = "forbid"
clear_with_drain = "forbid"
clone_on_copy = "forbid"
clone_on_ref_ptr = "forbid"
cloned_instead_of_copied = "forbid"
cloned_ref_to_slice_refs = "forbid"
cmp_null = "forbid"
cmp_owned = "forbid"
collapsible_else_if = "forbid"
collapsible_if = "deny"
collapsible_match = "forbid"
collapsible_str_replace = "forbid"
comparison_chain = "forbid"
comparison_to_empty = "forbid"
copy_iterator = "forbid"
create_dir = "forbid"
dbg_macro = "forbid"
decimal_literal_representation = "forbid"
default_constructed_unit_structs = "forbid"
default_instead_of_iter_empty = "forbid"
default_numeric_fallback = "forbid"
default_trait_access = "forbid"
default_union_representation = "forbid"
deprecated_cfg_attr = "forbid"
deprecated_clippy_cfg_attr = "forbid"
deref_addrof = "forbid"
deref_by_slicing = "forbid"
derivable_impls = "forbid"
derive_partial_eq_without_eq = "forbid"
doc_comment_double_space_linebreaks = "forbid"
doc_include_without_cfg = "forbid"
doc_lazy_continuation = "forbid"
doc_link_code = "forbid"
doc_link_with_quotes = "forbid"
doc_markdown = "forbid"
doc_overindented_list_items = "forbid"
doc_paragraphs_missing_punctuation = "forbid"
double_comparisons = "forbid"
double_ended_iterator_last = "forbid"
double_must_use = "forbid"
double_parens = "forbid"
drain_collect = "forbid"
duplicate_underscore_argument = "forbid"
duration_subsec = "forbid"
elidable_lifetime_names = "forbid"
empty_drop = "forbid"
empty_enum_variants_with_brackets = "forbid"
empty_enums = "forbid"
empty_structs_with_brackets = "forbid"
enum_glob_use = "forbid"
enum_variant_names = "forbid"
equatable_if_let = "deny"
err_expect = "forbid"
error_impl_error = "forbid"
excessive_nesting = "forbid"
excessive_precision = "forbid"
expect_fun_call = "forbid"
expl_impl_clone_on_copy = "forbid"
explicit_auto_deref = "forbid"
explicit_counter_loop = "forbid"
explicit_deref_methods = "forbid"
explicit_into_iter_loop = "forbid"
explicit_iter_loop = "forbid"
explicit_write = "forbid"
extend_with_drain = "forbid"
extra_unused_lifetimes = "forbid"
extra_unused_type_parameters = "forbid"
field_reassign_with_default = "forbid"
filter_map_bool_then = "forbid"
filter_map_identity = "forbid"
filter_map_next = "forbid"
filter_next = "forbid"
flat_map_identity = "forbid"
flat_map_option = "forbid"
float_cmp = "forbid"
float_cmp_const = "forbid"
fn_params_excessive_bools = "forbid"
fn_to_numeric_cast = "forbid"
fn_to_numeric_cast_any = "forbid"
for_kv_map = "forbid"
format_collect = "forbid"
format_in_format_args = "forbid"
format_push_string = "forbid"
from_iter_instead_of_collect = "forbid"
from_over_into = "forbid"
from_str_radix_10 = "forbid"
get_first = "forbid"
get_last_with_len = "forbid"
get_unwrap = "forbid"
identity_op = "forbid"
if_not_else = "forbid"
if_same_then_else = "forbid"
if_then_some_else_none = "forbid"
ignore_without_reason = "forbid"
ignored_unit_patterns = "forbid"
impl_trait_in_params = "forbid"
implicit_clone = "forbid"
implicit_hasher = "forbid"
implicit_saturating_add = "forbid"
implicit_saturating_sub = "forbid"
implied_bounds_in_impls = "forbid"
inconsistent_digit_grouping = "forbid"
inconsistent_struct_constructor = "forbid"
index_refutable_slice = "forbid"
inefficient_to_string = "forbid"
infallible_destructuring_match = "forbid"
inherent_to_string = "forbid"
init_numbered_fields = "forbid"
inline_always = "forbid"
inspect_for_each = "forbid"
int_plus_one = "forbid"
into_iter_on_ref = "forbid"
into_iter_without_iter = "forbid"
io_other_error = "forbid"
ip_constant = "forbid"
is_digit_ascii_radix = "forbid"
items_after_statements = "forbid"
items_after_test_module = "forbid"
iter_cloned_collect = "forbid"
iter_count = "forbid"
iter_filter_is_ok = "forbid"
iter_filter_is_some = "forbid"
iter_kv_map = "forbid"
iter_next_slice = "forbid"
iter_not_returning_iterator = "forbid"
iter_nth = "forbid"
iter_nth_zero = "forbid"
iter_on_empty_collections = "forbid"
iter_on_single_items = "forbid"
iter_overeager_cloned = "forbid"
iter_skip_next = "forbid"
iter_with_drain = "forbid"
iter_without_into_iter = "forbid"
just_underscores_and_digits = "forbid"
large_const_arrays = "forbid"
large_digit_groups = "forbid"
large_enum_variant = "forbid"
large_futures = "forbid"
large_include_file = "forbid"
large_stack_arrays = "forbid"
large_types_passed_by_value = "forbid"
legacy_numeric_constants = "forbid"
len_without_is_empty = "forbid"
len_zero = "forbid"
let_and_return = "forbid"
let_unit_value = "forbid"
let_with_type_underscore = "forbid"
linkedlist = "forbid"
lossy_float_literal = "forbid"
macro_use_imports = "forbid"
manual_abs_diff = "forbid"
manual_assert = "forbid"
manual_async_fn = "forbid"
manual_bits = "forbid"
manual_c_str_literals = "forbid"
manual_clamp = "forbid"
manual_contains = "forbid"
manual_dangling_ptr = "forbid"
manual_div_ceil = "forbid"
manual_filter = "forbid"
manual_filter_map = "forbid"
manual_find = "forbid"
manual_find_map = "forbid"
manual_flatten = "forbid"
manual_hash_one = "forbid"
manual_ignore_case_cmp = "forbid"
manual_inspect = "forbid"
manual_instant_elapsed = "forbid"
manual_is_ascii_check = "forbid"
manual_is_finite = "forbid"
manual_is_infinite = "forbid"
manual_is_multiple_of = "forbid"
manual_is_power_of_two = "forbid"
manual_is_variant_and = "forbid"
manual_let_else = "forbid"
manual_main_separator_str = "forbid"
manual_map = "forbid"
manual_memcpy = "forbid"
manual_midpoint = "forbid"
manual_next_back = "forbid"
manual_non_exhaustive = "forbid"
manual_ok_err = "forbid"
manual_ok_or = "forbid"
manual_option_as_slice = "forbid"
manual_pattern_char_comparison = "forbid"
manual_range_contains = "forbid"
manual_range_patterns = "forbid"
manual_rem_euclid = "forbid"
manual_repeat_n = "forbid"
manual_retain = "forbid"
manual_rotate = "forbid"
manual_saturating_arithmetic = "forbid"
manual_slice_fill = "forbid"
manual_slice_size_calculation = "forbid"
manual_split_once = "forbid"
manual_str_repeat = "forbid"
manual_string_new = "forbid"
manual_strip = "forbid"
manual_swap = "forbid"
manual_try_fold = "forbid"
manual_unwrap_or = "forbid"
manual_unwrap_or_default = "forbid"
manual_while_let_some = "forbid"
many_single_char_names = "forbid"
map_all_any_identity = "forbid"
map_clone = "forbid"
map_collect_result_unit = "forbid"
map_entry = "forbid"
map_err_ignore = "forbid"
map_flatten = "forbid"
map_identity = "forbid"
map_unwrap_or = "forbid"
map_with_unused_argument_over_ranges = "forbid"
match_as_ref = "forbid"
match_bool = "forbid"
match_like_matches_macro = "forbid"
match_overlapping_arm = "forbid"
match_ref_pats = "deny"
match_result_ok = "forbid"
match_same_arms = "forbid"
match_single_binding = "forbid"
match_wild_err_arm = "forbid"
match_wildcard_for_single_variants = "forbid"
mem_replace_option_with_none = "forbid"
mem_replace_option_with_some = "forbid"
mem_replace_with_default = "forbid"
missing_const_for_fn = "forbid"
missing_const_for_thread_local = "forbid"
missing_enforced_import_renames = "forbid"
missing_errors_doc = "forbid"
missing_fields_in_debug = "forbid"
missing_panics_doc = "deny"
missing_safety_doc = "forbid"
missing_spin_loop = "forbid"
mixed_attributes_style = "forbid"
mixed_case_hex_literals = "forbid"
module_inception = "forbid"
module_name_repetitions = "forbid"
multiple_inherent_impl = "deny"
multiple_unsafe_ops_per_block = "forbid"
must_use_candidate = "forbid"
must_use_unit = "forbid"
mut_mut = "forbid"
mutex_atomic = "forbid"
mutex_integer = "forbid"
needless_arbitrary_self_type = "forbid"
needless_as_bytes = "forbid"
needless_bitwise_bool = "forbid"
needless_bool = "forbid"
needless_bool_assign = "forbid"
needless_borrow = "forbid"
needless_borrowed_reference = "forbid"
needless_borrows_for_generic_args = "forbid"
needless_character_iteration = "forbid"
needless_collect = "forbid"
needless_continue = "forbid"
needless_doctest_main = "forbid"
needless_else = "forbid"
needless_for_each = "forbid"
needless_ifs = "forbid"
needless_late_init = "forbid"
needless_lifetimes = "forbid"
needless_match = "forbid"
needless_option_as_deref = "forbid"
needless_option_take = "forbid"
needless_parens_on_range_literals = "forbid"
needless_pass_by_ref_mut = "deny"
needless_pass_by_value = "deny"
needless_pub_self = "forbid"
needless_question_mark = "forbid"
needless_range_loop = "forbid"
needless_raw_string_hashes = "forbid"
needless_raw_strings = "forbid"
needless_return = "deny"
needless_return_with_question_mark = "forbid"
needless_splitn = "forbid"
needless_update = "forbid"
neg_cmp_op_on_partial_ord = "forbid"
neg_multiply = "forbid"
negative_feature_names = "forbid"
new_ret_no_self = "forbid"
new_without_default = "forbid"
no_effect = "forbid"
no_effect_underscore_binding = "forbid"
no_mangle_with_rust_abi = "forbid"
non_ascii_literal = "forbid"
non_canonical_clone_impl = "forbid"
non_canonical_partial_ord_impl = "forbid"
non_minimal_cfg = "forbid"
non_std_lazy_statics = "forbid"
nonminimal_bool = "forbid"
nonstandard_macro_braces = "forbid"
obfuscated_if_else = "forbid"
ok_expect = "forbid"
only_used_in_recursion = "forbid"
op_ref = "forbid"
option_as_ref_cloned = "forbid"
option_as_ref_deref = "forbid"
option_filter_map = "forbid"
option_if_let_else = "forbid"
option_map_or_none = "forbid"
option_map_unit_fn = "forbid"
option_option = "forbid"
or_fun_call = "forbid"
or_then_unwrap = "forbid"
owned_cow = "forbid"
partialeq_ne_impl = "forbid"
partialeq_to_none = "forbid"
pathbuf_init_then_push = "forbid"
precedence = "forbid"
precedence_bits = "forbid"
print_literal = "forbid"
print_with_newline = "forbid"
println_empty_string = "forbid"
ptr_arg = "forbid"
ptr_as_ptr = "forbid"
ptr_cast_constness = "forbid"
ptr_eq = "forbid"
ptr_offset_with_cast = "forbid"
pub_underscore_fields = "forbid"
pub_without_shorthand = "forbid"
question_mark = "forbid"
range_minus_one = "forbid"
range_plus_one = "forbid"
range_zip_with_len = "forbid"
rc_buffer = "forbid"
rc_mutex = "forbid"
readonly_write_lock = "forbid"
redundant_allocation = "forbid"
redundant_as_str = "forbid"
redundant_async_block = "forbid"
redundant_at_rest_pattern = "forbid"
redundant_clone = "forbid"
redundant_closure = "forbid"
redundant_closure_call = "forbid"
redundant_closure_for_method_calls = "forbid"
redundant_comparisons = "forbid"
redundant_else = "forbid"
redundant_feature_names = "forbid"
redundant_field_names = "forbid"
redundant_guards = "forbid"
redundant_iter_cloned = "forbid"
redundant_locals = "forbid"
redundant_pattern = "forbid"
redundant_pattern_matching = "forbid"
redundant_slicing = "forbid"
redundant_static_lifetimes = "forbid"
redundant_test_prefix = "forbid"
redundant_type_annotations = "forbid"
ref_as_ptr = "forbid"
ref_binding_to_reference = "forbid"
ref_option = "forbid"
ref_option_ref = "forbid"
renamed_function_params = "deny"
repeat_once = "forbid"
replace_box = "forbid"
reserve_after_initialization = "forbid"
rest_pat_in_fully_bound_structs = "forbid"
result_filter_map = "forbid"
result_large_err = "forbid"
result_map_or_into_option = "forbid"
result_map_unit_fn = "forbid"
result_unit_err = "forbid"
return_and_then = "forbid"
return_self_not_must_use = "forbid"
same_functions_in_if_condition = "forbid"
same_item_push = "forbid"
search_is_some = "forbid"
seek_from_current = "forbid"
seek_to_start_instead_of_rewind = "forbid"
self_named_constructors = "forbid"
self_named_module_files = "forbid"
self_only_used_in_recursion = "forbid"
semicolon_if_nothing_returned = "forbid"
semicolon_outside_block = "forbid"
shadow_unrelated = "forbid"
short_circuit_statement = "forbid"
should_implement_trait = "forbid"
should_panic_without_expect = "forbid"
similar_names = "forbid"
single_char_add_str = "forbid"
single_char_lifetime_names = "forbid"
single_char_pattern = "forbid"
single_component_path_imports = "forbid"
single_element_loop = "forbid"
single_match = "forbid"
single_match_else = "forbid"
single_option_map = "forbid"
skip_while_next = "forbid"
sliced_string_as_bytes = "forbid"
slow_vector_initialization = "forbid"
stable_sort_primitive = "forbid"
std_instead_of_alloc = "deny"
std_instead_of_core = "deny"
str_split_at_newline = "forbid"
str_to_string = "forbid"
string_add = "forbid"
string_add_assign = "forbid"
string_extend_chars = "forbid"
string_from_utf8_as_bytes = "forbid"
string_lit_as_bytes = "forbid"
string_lit_chars_any = "forbid"
strlen_on_c_strings = "forbid"
struct_excessive_bools = "forbid"
struct_field_names = "forbid"
swap_with_temporary = "forbid"
tabs_in_doc_comments = "forbid"
to_digit_is_some = "forbid"
to_string_in_format_args = "forbid"
to_string_trait_impl = "forbid"
todo = "forbid"
too_long_first_doc_paragraph = "forbid"
too_many_arguments = "forbid"
too_many_lines = "deny"
toplevel_ref_arg = "forbid"
trait_duplication_in_bounds = "forbid"
transmute_ptr_to_ptr = "forbid"
transmutes_expressible_as_ptr_casts = "forbid"
trivially_copy_pass_by_ref = "deny"
tuple_array_conversions = "forbid"
type_complexity = "forbid"
type_repetition_in_bounds = "forbid"
undocumented_unsafe_blocks = "forbid"
unicode_not_nfc = "forbid"
uninlined_format_args = "forbid"
unnecessary_box_returns = "forbid"
unnecessary_cast = "forbid"
unnecessary_clippy_cfg = "forbid"
unnecessary_debug_formatting = "forbid"
unnecessary_fallible_conversions = "forbid"
unnecessary_filter_map = "forbid"
unnecessary_find_map = "forbid"
unnecessary_first_then_check = "forbid"
unnecessary_fold = "forbid"
unnecessary_get_then_check = "forbid"
unnecessary_join = "forbid"
unnecessary_lazy_evaluations = "forbid"
unnecessary_literal_bound = "forbid"
unnecessary_literal_unwrap = "forbid"
unnecessary_map_on_constructor = "forbid"
unnecessary_map_or = "forbid"
unnecessary_min_or_max = "forbid"
unnecessary_mut_passed = "forbid"
unnecessary_operation = "forbid"
unnecessary_option_map_or_else = "forbid"
unnecessary_owned_empty_strings = "forbid"
unnecessary_result_map_or_else = "forbid"
unnecessary_safety_comment = "forbid"
unnecessary_safety_doc = "forbid"
unnecessary_self_imports = "forbid"
unnecessary_semicolon = "forbid"
unnecessary_sort_by = "forbid"
unnecessary_struct_initialization = "deny"
unnecessary_to_owned = "forbid"
unnecessary_unwrap = "forbid"
unnecessary_wraps = "forbid"
unneeded_field_pattern = "forbid"
unneeded_struct_pattern = "forbid"
unneeded_wildcard_pattern = "forbid"
unnested_or_patterns = "forbid"
unreachable = "forbid"
unreadable_literal = "forbid"
unseparated_literal_suffix = "deny"
unused_async = "forbid"
unused_enumerate_index = "forbid"
unused_format_specs = "forbid"
unused_peekable = "forbid"
unused_result_ok = "forbid"
unused_rounding = "forbid"
unused_self = "forbid"
unused_trait_names = "forbid"
unused_unit = "forbid"
unusual_byte_groupings = "forbid"
unwrap_or_default = "forbid"
upper_case_acronyms = "forbid"
use_self = "forbid"
useless_asref = "forbid"
useless_concat = "forbid"
useless_conversion = "forbid"
useless_format = "forbid"
useless_let_if_seq = "forbid"
useless_vec = "forbid"
vec_box = "forbid"
vec_init_then_push = "forbid"
verbose_bit_mask = "forbid"
verbose_file_reads = "forbid"
waker_clone_wake = "forbid"
while_let_loop = "forbid"
while_let_on_iterator = "forbid"
wildcard_dependencies = "forbid"
wildcard_enum_match_arm = "deny"
wildcard_imports = "forbid"
wildcard_in_or_patterns = "forbid"
write_literal = "forbid"
write_with_newline = "forbid"
writeln_empty_string = "forbid"
wrong_self_convention = "forbid"
zero_prefixed_literal = "forbid"
zero_ptr = "forbid"
zero_sized_map_values = "forbid"
