[package]
name = "spider-cli"
version = "1.0.0"
edition = "2024"

[dependencies]
turing-machine-lifter = { path = "../Sources/TuringMachine" }
web-assembly-lifter = { path = "../Sources/WebAssembly/Lifter" }

ir-graph = { path = "../IR/Graph" }
ir-visitor = { path = "../IR/Visitor" }

json-printer = { path = "../Targets/Json" }

luajit-tree = { path = "../Targets/LuaJIT/Tree" }
luajit-builder = { path = "../Targets/LuaJIT/Builder" }
luajit-printer = { path = "../Targets/LuaJIT/Printer" }

luanoffi-tree = { path = "../Targets/LuaNoFFI/Tree" }
luanoffi-builder = { path = "../Targets/LuaNoFFI/Builder" }
luanoffi-printer = { path = "../Targets/LuaNoFFI/Printer" }

luau-tree = { path = "../Targets/Luau/Tree" }
luau-builder = { path = "../Targets/Luau/Builder" }
luau-printer = { path = "../Targets/Luau/Printer" }

clap = { version = "4.5.23", default-features = false, features = [
	"color",
	"derive",
	"error-context",
	"help",
	"std",
	"suggestions",
	"usage",
] }

wasmparser = { workspace = true, features = ["validate"] }
