[package]
name = "conformance"
version = "1.0.0"
edition = "2024"

[lints]
workspace = true

[dev-dependencies]
web-assembly-lifter = { path = "../Sources/WebAssembly/Lifter" }
ir-graph = { path = "../IR/Graph" }
ir-visitor = { path = "../IR/Visitor" }

luau-builder = { path = "../Targets/Luau/Builder" }
luau-printer = { path = "../Targets/Luau/Printer" }

luajit-builder = { path = "../Targets/LuaJIT/Builder" }
luajit-printer = { path = "../Targets/LuaJIT/Printer" }

luanoffi-builder = { path = "../Targets/LuaNoFFI/Builder" }
luanoffi-printer = { path = "../Targets/LuaNoFFI/Printer" }
luanoffi-tree = { path = "../Targets/LuaNoFFI/Tree" }

datatest-stable = "0.3.2"
wast = "222.0.0"

[[test]]
name = "luau"
harness = false

[[test]]
name = "luajit"
harness = false

[[test]]
name = "luanoffi"
harness = false
