param(
    [Parameter(Mandatory = $true)]
    [string]$InputPath,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath,

    [Parameter(Mandatory = $true)]
    [string]$SymbolName
)

$bytes = [System.IO.File]::ReadAllBytes((Resolve-Path $InputPath))
$builder = New-Object System.Text.StringBuilder

[void]$builder.AppendLine("/* generated by embed_asset.ps1 */")
[void]$builder.AppendLine("#ifndef " + ($SymbolName.ToUpperInvariant()) + "_H")
[void]$builder.AppendLine("#define " + ($SymbolName.ToUpperInvariant()) + "_H")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("static const unsigned int ${SymbolName}_size = " + $bytes.Length + "u;")
[void]$builder.AppendLine("static const unsigned char $SymbolName" + "[] = {")

for ($index = 0; $index -lt $bytes.Length; $index += 12) {
    $chunk = $bytes[$index..([Math]::Min($index + 11, $bytes.Length - 1))]
    $hex = ($chunk | ForEach-Object { "0x{0:X2}" -f $_ }) -join ", "
    [void]$builder.AppendLine("    " + $hex + ",")
}

[void]$builder.AppendLine("};")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("#endif")

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Resolve-Path -LiteralPath (Split-Path $OutputPath -Parent)).Path + "\" + (Split-Path $OutputPath -Leaf), $builder.ToString(), $utf8NoBom)
