#ifndef REAL_WORLD_LIBJPEG_TURBO_JCONFIG_H
#define REAL_WORLD_LIBJPEG_TURBO_JCONFIG_H

#define JPEG_LIB_VERSION 62
#define LIBJPEG_TURBO_VERSION "3.1.91"
#define LIBJPEG_TURBO_VERSION_NUMBER 3001091
#define MEM_SRCDST_SUPPORTED 1
#ifndef BITS_IN_JSAMPLE
#define BITS_IN_JSAMPLE 8
#endif
#define D_ARITH_CODING_SUPPORTED 1

#endif
