name: Conformance

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [trunk]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Conformance - ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux x64
            os: ubuntu-latest
            luajit: sudo apt-get update && sudo apt-get install -y luajit

          - name: macOS ARM64
            os: macos-latest
            luajit: brew install luajit

          - name: Windows x64
            os: windows-latest
            luajit: ""

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          submodules: recursive

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5

      - name: Install LuaJIT
        if: matrix.luajit != ''
        run: ${{ matrix.luajit }}

      - name: Format
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Build
        run: cargo build --verbose

      - name: Unit tests
        run: cargo test --workspace --exclude conformance --verbose

      - name: Conformance (LuaJIT target)
        if: matrix.luajit != ''
        run: cargo test -p conformance --test luajit --verbose

      - name: Conformance (lua-no-ffi target)
        if: matrix.luajit != ''
        run: cargo test -p conformance --test luanoffi --verbose
